[project]
name = "ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "grpcio>=1.75.1",
    "grpcio-tools>=1.75.1",
    "kagglehub>=0.3.13",
    "torch>=2.8.0",
]
