[project]
name = "raspberry-camera"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.119.0",
    "numpy>=2.3.3",
    "opencv-python>=4.11.0.86",
    "uvicorn>=0.37.0",
]
